//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public int Pagenum { get; set; }
        public string Paper { get; set; }
        public int DealID { get; set; }
    
        public virtual Deal Deal { get; set; }
    }
}
